### ISSUE TITLE
Roles and Authority

### ISSUE THREAD

**Issue by kachun333** [Five-Fishes/Club-Management-React-Client#10]
[Type of Roles]
1. Member
2. Event Crew
3. Event Head
4. Admin // hi-com 
5. CC Head 

CC head give authority to new CC head mechanism/ business rules is yet to decide

**Comment by junzai97** [comment]
Authorities of each roles in the **Event Module** can be refer in image below
![Roles   Authorities](https://user-images.githubusercontent.com/37231490/108513129-1fc18280-72fd-11eb-9371-b109c9f3f0ec.PNG)

**Comment by HowardYaw** [comment]
**Finance Module** will only be accessed by user with Administrator role
