### ISSUE TITLE
Event activity duration rounding should round off correctly

### ISSUE THREAD

**Issue by LUXIANZE** [Five-Fishes/Club-Management-React-Client#117]
Current Behaviour:
- Does not round off 1 hour to 1 hour, but few minutes less than one hour
Expected Behaviour:
- duration will be save correctly, 1 hour should be 1 hour
- 
Steps To Reproduce?: 
1. Visit on going event as admin/event head
2. Add event activity
3. Set event activity with perfectly rounded duration like: 1hour /1day

Screenshots of UI?:
Additional Details?:

**Comment by HowardYaw** [comment]
Might cause by Database type that rounded off to 2 decimal values

after checking `duration-utils` the round off is to 5 decimal values

**Comment by HowardYaw** [comment]
Suppose to fix in Server side

DB is storing duration_in_day with DECIMAL(21,2)

Convert it to duration_in_second can resolve but required FE pass in second as well
