### ISSUE TITLE
Event activity not returned in reverse chronology

### ISSUE THREAD

**Issue by LUXIANZE** [Five-Fishes/Club-Management-React-Client#119]
Current Behaviour:
- Event activity no any chronological order

Expected Behaviour:
- Event activity should display as list in reverse chronological order

Steps To Reproduce?: 
1. Visit on going event as admin/event head
2. Create event activity of a random future date
3. Create event activity of a date earlier than the random future date just now
4. The reverse chronological order is not applicable

Screenshots of UI?:
Additional Details?:

**Comment by HowardYaw** [comment]
@LUXIANZE 
this issue is expected behavior is
I had one Event Activity at 20/05/2021 10:00 pm created
I should not allow creating any Event Activity earlier like 19/05/2021 10:00 am?

**Comment by LUXIANZE** [comment]
@HowardYaw No, let's say:
1. Create activity **breakfast** with time 10.00am
2. Create activity **gather and head count** with time 9.00am
3. When server return, although **gather and head count** is created later. The list should show as

| **gather and head count** | 9.00 am |
|-|-|
| **breakfast** | 10.00 am | 

I can still add activity earlier, but has to be sorted in reverse chronological order

**Comment by HowardYaw** [comment]
@LUXIANZE 
then it is same as #104 ?

**Comment by HowardYaw** [comment]
Closed due to duplicated with #104
