### ISSUE TITLE
Prepare Finance Reporting Page Mockup

### ISSUE THREAD

**Issue by LUXIANZE** [Five-Fishes/Club-Management-React-Client#126]
Page Url: N/A
Module: Finance
Authority:
- CC Board

Usage: View CC financial overview in charting format information

[Figma Link](https://www.figma.com/proto/Le9FADTclndB29aP8Yju42/Third-CC-Web-App-(Copy)?node-id=452%3A700&scaling=min-zoom&page-id=19%3A2)

- [x] Mockup
- [x] Consensus from @kachun333 @HowardYaw @junzai97 @CarlosSia

**Comment by HowardYaw** [comment]
@LUXIANZE 
1. Finance Report no need Add Button maybe
2. Can put some title/description to the report? like mention Year Session?
3. Bad Debt and Invalid Expense is not the real transaction right? Why not just show real/success Transaction in Chart only?

**Comment by LUXIANZE** [comment]
@HowardYaw 
1. Noted on this, I think we discussed to move the create transaction button to the side nav there
2. Yes this is good suggestion
3. I think although they are not transacted, but it affects our asset, consider
    - When Bad Debt might be **not transacted**, but when we have too much bad debt, we know we are experiencing big loss
    - When user look at the over view and realise the two **Invalid transaction** section are in abnormal ratio compared to real transaction, then CC financial might be unhealthy

**Comment by HowardYaw** [comment]
@LUXIANZE 
extended from 3
- so the Donut Chart is ratio of `number of transations` or `transaction amount`?
- What Insight/analysis from the Donut Chart are providing?

**Comment by LUXIANZE** [comment]
@HowardYaw 

- Doughnut chart is the amount of each transaction types (income, expense, bad debt, invalid expense)
- Doughnut chart is where user can see the ratio of a type to all transactions (in percentage)
