### ISSUE TITLE
Fetch Account & Store in Redux Global State

### ISSUE THREAD

**Issue by kachun333** [Five-Fishes/Club-Management-React-Client#37]
Page Url: N/A
Module: Account
Authority: N/A

# Motivation
when the user arrives at our app, the app will call the fetch account endpoint to fetch all the user information. The response body shall be cache in the redux global state. 

# Expected Global State
```
  id: number; // userId
  firstName: string;
  email: string;
  imageUrl: string;
  authorities: string[];
  isCurrentCCHead: boolean;
  isCurrentAdministrator: boolean;
  eventHeadIds: number[]; // an array of eventId
  eventCrewIds: number[]; // an array of eventId
```

- [ ] Development
- [ ] Unit Test

**Comment by HowardYaw** [comment]
@kachun333 is this being resolved in #54 ?
