### ISSUE TITLE
App Header

### ISSUE THREAD

**Issue by kachun333** [Five-Fishes/Club-Management-React-Client#4]
Page Url: /
Module: App Shell
Components: (if any)
- [x] Header

Usage: 
1. user can click hamburger icon to view sidenav
2. user can click brand icon to go to home page
3. user can click language dropdown nav to select nav
4. user can click account dropdown nav
      1. if the user is NOT signed in, it will show 
              - sign in option
              - register option
      2. if the user is signed in, it will show 
              - setting option
              - password option
              - sign out option

**Comment by kachun333** [comment]
#### Desktop view
![image](https://user-images.githubusercontent.com/34387770/100985204-8d30f480-3500-11eb-8454-28310d5ba13f.png)

#### Mobile view
![image](https://user-images.githubusercontent.com/34387770/100985159-7b4f5180-3500-11eb-8a18-dcfa2ea74a96.png)

**Comment by HowardYaw** [comment]
@kachun333 the icon is seriously?
